name: First Workflow
on : workflow_dispatch
jobs:
  first-job:
    runs-on: Windows Server 2022 64-bit
    steps:
      - name: Print greeting
        run: echo "Hello World!"
      - name: Print goodbye
        run: echo "Done - bye!"
